minimum_pre_commit_version: "4.3.0"
default_stages: [pre-commit, pre-push]

exclude: |
  (?x)(
    ^data/json_data/.*|
    ^src/logs/.*|
    \.log$|
    ^example_env$
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.12
